name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Hub login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and publish
      uses: docker/build-push-action@v4
      with:
        context: ./QRClipboard
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{secrets.DOCKER_USER}}/qrclipboard:latest